// 🎧 Our Soundtrack — "24 lagu yang kamu suka, dengan sedikit bagian dari aku di
// dalamnya." SEMUA teks & lagu ada di sini. Edit bebas: ganti judul, artis,
// youtubeId, dan pesan per lagu. Nggak perlu ngoprek komponen lain.
//
// Jumlah lagu OTOMATIS ngikutin panjang array `songs`.
//
// Cara ngambil youtubeId: dari link YouTube-nya.
//   https://youtu.be/3UdVruU2qGc            -> "3UdVruU2qGc"
//   https://www.youtube.com/watch?v=3UdVruU2qGc -> "3UdVruU2qGc"
// startSeconds: mulai dari detik ke berapa (opsional; 0 = awal).
// cover: opsional. Kosongin ("") biar otomatis pakai thumbnail YouTube-nya.
// message: tiap string = satu paragraf, muncul perlahan satu per satu.

export type SoundtrackSong = {
  title: string;
  artist: string;
  youtubeId: string;
  startSeconds?: number;
  cover?: string;
  message: string[];
};

export const soundtrackConfig = {
  // 🌙 Layar pembuka.
  opening: {
    title: "Our Soundtrack",
    subtitle: "{n} songs. {n} little pieces of us.", // {n} otomatis = jumlah lagu
    beginLabel: "Begin the journey ♡",
    resumeLabel: "Lanjutkan",
    restartLabel: "Mulai dari awal",
  },

  introTeaser: "Ada sesuatu yang ingin aku ceritakan tentang lagu ini…",

  nextLabel: "Lagu berikutnya →",
  lastNextLabel: "Sampai di penghujung →",
  prevLabel: "sebelumnya",
  scrollHint: "gulir pelan-pelan",
  muteOnLabel: "Matikan lagu",
  muteOffLabel: "Nyalakan lagu",

  // 🎼 24 lagu dari playlist kamu (urut).
  songs: [
    {
      title: "Siapkah Kau 'Tuk Jatuh Cinta Lagi",
      artist: "Hivi!",
      youtubeId: "zcDkUXW8SMQ",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku nggak tahu sejak kapan lagu ini menjadi salah satu lagu yang kamu suka, dan mungkin sebelum ada aku pun lagu ini sudah punya tempatnya sendiri di hidupmu. Tapi sekarang, aku ingin sedikit mengambil bagian dari lagu ini dan menjadikannya sesuatu yang mengingatkanmu kepadaku.",
        "Karena kalau ada satu hal yang ingin aku lakukan berkali-kali, mungkin itu adalah jatuh cinta kepadamu. Bukan cuma sekali, bukan cuma saat semuanya terasa indah, tapi juga setelah melewati hari-hari yang biasa, setelah melihat sisi-sisimu yang mungkin nggak selalu sempurna, dan setelah mengenalmu lebih jauh.",
        "Aku ingin tetap punya alasan untuk melihatmu seperti pertama kali aku mengenalmu. Tetap merasa senang ketika melihat namamu muncul, tetap tersenyum ketika kamu melakukan hal kecil yang mungkin menurutmu biasa saja.",
        "Jadi kalau suatu hari nanti lagu ini terdengar lagi tanpa aku di sampingmu, semoga ada sedikit bagian dari dirimu yang berkata, “Oh, ini lagu yang pernah dia kasih untukku.”",
        "Dan kalau saat itu kamu tersenyum, berarti lagu ini sudah berhasil melakukan tugasnya.",
      ],
    },
    {
      title: "Ceritanya Jatuh Cinta",
      artist: "Aku Jeje",
      youtubeId: "joKMsvaR9gQ", // alternatif audio: 8PgLB6cM6HU
      startSeconds: 0,
      cover: "",
      message: [
        "Lucu kalau dipikir-pikir bagaimana seseorang bisa masuk ke dalam hidup kita tanpa pernah benar-benar kita rencanakan. Awalnya mungkin hanya percakapan biasa, perhatian kecil, atau sekadar rasa penasaran terhadap seseorang.",
        "Lalu hari demi hari berlalu, kita mulai terbiasa dengan kehadirannya. Mulai menunggu pesan darinya. Mulai mencari-cari alasan untuk bercerita. Sampai suatu hari kita sadar bahwa orang itu ternyata sudah menjadi bagian dari rutinitas kita.",
        "Mungkin begitulah ceritanya kita.",
        "Aku nggak tahu apakah ada satu titik yang bisa disebut sebagai awal dari semuanya. Tapi aku tahu ada banyak momen kecil yang akhirnya membawa aku sampai di sini, sampai aku bisa menyebut kamu sebagai seseorang yang begitu berarti buatku.",
        "Dan mungkin memang begitu cara cinta bekerja. Nggak selalu datang dengan sesuatu yang besar. Kadang dia datang diam-diam, tumbuh dari kebiasaan kecil, lalu tiba-tiba kita sadar kalau ternyata kita sudah jatuh terlalu jauh.",
        "Kalau nanti kamu mendengar lagu ini lagi, aku ingin kamu ingat bahwa di antara begitu banyak cerita yang mungkin kamu punya dalam hidupmu, ada satu cerita yang pernah membuat seseorang jatuh cinta kepadamu.",
        "Dan orang itu adalah aku.",
      ],
    },
    {
      title: "Jatuh Hati",
      artist: "Raisa",
      youtubeId: "9gY0vpjbDuA",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku rasa jatuh hati kepadamu bukan sesuatu yang terjadi hanya sekali.",
        "Ada saat ketika aku pertama kali tertarik kepadamu. Ada saat ketika aku mulai mengenalmu lebih jauh. Ada saat ketika aku menemukan sisi lain dari dirimu yang sebelumnya nggak pernah aku tahu.",
        "Dan anehnya, setiap kali aku merasa sudah cukup mengenalmu, selalu ada hal baru yang membuatku jatuh hati lagi.",
        "Mungkin dari caramu berbicara. Cara kamu tertawa. Cara kamu melakukan sesuatu yang sebenarnya sederhana tapi entah kenapa terlihat begitu menarik ketika kamu yang melakukannya. Bahkan mungkin dari hal-hal kecil yang nggak pernah kamu sadari.",
        "Aku nggak ingin mencintai hanya versi dirimu yang terlihat sempurna. Aku ingin mengenalmu sebagai manusia yang punya hari baik dan buruk, punya kekhawatiran, punya kekurangan, punya mimpi, dan punya banyak hal yang masih ingin dicapai.",
        "Karena buatku, jatuh hati yang sebenarnya bukan ketika kita menemukan seseorang yang sempurna.",
        "Tapi ketika kita sudah tahu bahwa seseorang itu nggak sempurna, lalu kita masih ingin memilihnya.",
        "Dan sampai sekarang, aku masih memilihmu.",
      ],
    },
    {
      title: "Mesra-mesraannya kecil-kecilan di sisa waktu",
      artist: "Sal Priadi",
      youtubeId: "aHxxbTq0TXE", // judul asli lagu: "…kecil-kecilan dulu"
      startSeconds: 0,
      cover: "",
      message: [
        "Aku suka hal-hal kecil.",
        "Aku suka membayangkan kita melakukan sesuatu yang sebenarnya nggak istimewa. Pergi makan tanpa tujuan khusus. Duduk berdua sambil membicarakan hal-hal nggak penting. Ketawa karena sesuatu yang bahkan mungkin nggak lucu. Atau cuma berada di tempat yang sama tanpa harus selalu melakukan sesuatu.",
        "Mungkin bagi orang lain itu bukan sesuatu yang spesial.",
        "Tapi buatku, kebahagiaan memang nggak selalu datang dalam bentuk sesuatu yang besar.",
        "Kadang kebahagiaan cuma berupa seseorang yang membuat kita nyaman menjadi diri sendiri.",
        "Dan kalau suatu hari waktu kita sedang sedikit, kesibukan sedang banyak, atau hidup sedang membawa kita ke arah yang berbeda-beda, aku ingin kita tetap punya ruang untuk melakukan hal-hal kecil seperti itu.",
        "Karena mungkin nanti bukan perjalanan besar yang paling kita ingat.",
        "Mungkin justru obrolan random tengah malam. Makan sederhana. Jalan tanpa tujuan. Atau momen ketika kita cuma duduk berdua dan merasa, “ternyata sesederhana ini ya, bahagia.”",
        "Kalau lagu ini mengingatkanmu pada sesuatu, semoga yang muncul adalah semua hal kecil yang pernah membuat kita merasa dekat.",
      ],
    },
    {
      title: "Besok kita pergi makan",
      artist: "Sal Priadi",
      youtubeId: "jYIcxdDuGMk",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku suka kalimat sederhana seperti “besok kita pergi makan.”",
        "Nggak terdengar seperti sesuatu yang luar biasa. Nggak ada rencana besar, nggak ada tempat mewah, nggak ada sesuatu yang harus dikenang seumur hidup.",
        "Tapi justru di situlah letak indahnya.",
        "Karena terkadang yang aku tunggu bukan makanannya. Bukan tempatnya. Bahkan bukan apa yang akan kita lakukan setelahnya.",
        "Aku cuma ingin ada seseorang yang bisa kuajak membuat rencana sederhana untuk hari esok.",
        "Dan kalau orang itu kamu, rasanya sudah cukup.",
        "Aku ingin punya banyak “besok” bersamamu. Besok pergi makan. Besok jalan sebentar. Besok ngobrol lagi. Besok cerita tentang hari ini. Besok tertawa karena hal yang sama.",
        "Karena pada akhirnya, mungkin kebahagiaan bukan tentang memiliki satu hari yang sempurna.",
        "Tapi tentang punya seseorang yang membuat kita menantikan hari berikutnya.",
        "Dan aku harap, untuk waktu yang lama, orang yang ingin kutemui di hari berikutnya masih tetap kamu.",
      ],
    },
    {
      title: "I'd like to watch you sleeping",
      artist: "Sal Priadi",
      youtubeId: "4OL6d6NZ3I0",
      startSeconds: 0,
      cover: "",
      message: [
        "Ada sesuatu yang menurutku sangat sederhana tapi intim dari melihat seseorang yang kita sayangi sedang tidur.",
        "Saat seseorang tidur, dia nggak sedang berusaha menjadi apa-apa. Nggak sedang berusaha terlihat cantik, nggak sedang berusaha terlihat kuat, nggak sedang memikirkan bagaimana orang lain melihatnya.",
        "Dia cuma sedang menjadi dirinya sendiri.",
        "Dan mungkin itu yang membuatnya terasa begitu dekat.",
        "Aku ingin kamu punya banyak malam yang tenang. Malam ketika kamu bisa meletakkan semua bebanmu sebentar, berhenti memikirkan hal-hal yang belum selesai, dan membiarkan dirimu beristirahat.",
        "Kalau suatu hari aku nggak bisa berada di sana untuk memastikan kamu baik-baik saja, setidaknya aku ingin kamu tahu bahwa pernah ada seseorang yang berharap kamu tidur dengan tenang setiap malam.",
        "Seseorang yang mungkin diam-diam selalu ingin memastikan bahwa hari yang panjang akhirnya berakhir dengan baik untukmu.",
        "Jadi kalau suatu malam lagu ini terdengar sebelum kamu tidur, anggap saja ada sedikit doa dariku yang ikut menemanimu malam itu.",
        "Tidur yang nyenyak, ya.",
        "Kamu sudah melakukan yang terbaik hari ini.",
      ],
    },
    {
      title: "Kita Lewati Berdua",
      artist: "Overnight",
      youtubeId: "__Pb1fO2H2A", // alternatif lyric video: g-G__u0Allw
      startSeconds: 0,
      cover: "",
      message: [
        "Aku nggak tahu apa saja yang akan kita temui di depan.",
        "Aku nggak bisa menjanjikan bahwa semuanya akan selalu mudah. Akan ada hari ketika kita lelah, salah paham, berbeda pendapat, atau mungkin sama-sama nggak tahu harus berbuat apa.",
        "Tapi kalau boleh berharap, aku ingin kita nggak hanya hadir ketika semuanya sedang baik-baik saja.",
        "Aku ingin kita juga belajar bagaimana caranya tetap tinggal ketika keadaan sedang nggak mudah.",
        "Karena menurutku, bersama seseorang bukan berarti kita harus selalu punya jawaban untuk semua masalah.",
        "Kadang cukup dengan mengatakan, “Nggak apa-apa, kita pikirin sama-sama.”",
        "Aku ingin kita punya keberanian untuk melewati hari-hari yang berat tanpa harus merasa bahwa kita harus menghadapi semuanya sendirian.",
        "Kalau suatu hari kamu takut dengan apa yang ada di depan, ingat saja bahwa kamu nggak harus mengetahui seluruh jalan untuk bisa melangkah.",
        "Kita bisa jalan pelan-pelan.",
        "Satu hari demi satu hari.",
        "Dan kalau perjalanan itu panjang, semoga kita bisa melewatinya berdua.",
      ],
    },
    {
      title: "Beautiful (feat. Camila Cabello)",
      artist: "Bazzi, Camila Cabello",
      youtubeId: "Uk1hv6h7O1Y",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku ingin kamu tahu bahwa menurutku kamu cantik bukan hanya ketika kamu sedang berusaha terlihat cantik.",
        "Ada sesuatu dari dirimu yang tetap indah ketika kamu sedang tertawa tanpa sadar, ketika kamu sedang cerita panjang tentang sesuatu yang kamu suka, ketika kamu sedang kesal, ketika rambutmu berantakan, atau ketika kamu bahkan nggak sadar sedang diperhatikan.",
        "Mungkin kamu nggak akan selalu melihat apa yang aku lihat ketika melihatmu.",
        "Kadang kita terlalu terbiasa dengan diri sendiri sampai lupa bahwa bagi seseorang, hal-hal yang kita anggap biasa justru bisa menjadi sesuatu yang sangat berarti.",
        "Jadi kalau suatu hari kamu merasa kurang cantik, kurang baik, atau kurang dari apa yang kamu inginkan, aku ingin kamu mengingat lagu ini.",
        "Bukan karena lagu ini mengatakan bahwa kamu sempurna.",
        "Tapi karena pernah ada seseorang yang melihatmu dan benar-benar merasa beruntung bisa mengenalmu.",
        "Dan orang itu melihat sesuatu yang mungkin belum selalu bisa kamu lihat sendiri.",
        "Aku harap kamu selalu ingat itu.",
      ],
    },
    {
      title: "Membasuh",
      artist: "Hindia, Rara Sekar",
      youtubeId: "emddwjzuNW4",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku tahu nggak semua hari akan terasa ringan.",
        "Ada hari ketika semuanya berjalan seperti yang kamu inginkan. Tapi ada juga hari ketika bangun dari tempat tidur saja rasanya sudah melelahkan.",
        "Kalau nanti ada hari seperti itu, aku ingin kamu tahu bahwa kamu nggak harus selalu terlihat kuat di depanku.",
        "Kamu boleh cerita.",
        "Kamu boleh diam.",
        "Kamu boleh menangis.",
        "Kamu boleh bilang bahwa hari ini berat.",
        "Kamu nggak harus selalu punya alasan untuk merasa lelah.",
        "Dan kalau aku nggak bisa memperbaiki semuanya, setidaknya aku ingin menjadi seseorang yang bisa mendengarkan tanpa membuatmu merasa harus menyembunyikan apa yang kamu rasakan.",
        "Aku ingin kehadiranku terasa seperti tempat untuk bernapas sebentar.",
        "Tempat di mana kamu nggak harus menjadi siapa-siapa selain dirimu sendiri.",
        "Jadi kalau suatu hari lagu ini menemanimu ketika sedang lelah, semoga kamu ingat bahwa ada seseorang yang selalu berharap setelah semua beratnya hari itu selesai, kamu bisa menemukan sedikit ketenangan.",
        "Istirahatlah.",
        "Besok kita coba lagi.",
      ],
    },
    {
      title: "everything u are",
      artist: "Hindia",
      youtubeId: "da4Xw2Kr79w",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku ingin mengenal semuanya tentang kamu.",
        "Bukan hanya sisi yang kamu tunjukkan ketika semuanya baik-baik saja, tapi juga sisi yang mungkin kamu sembunyikan karena takut orang lain nggak akan mengerti.",
        "Aku ingin tahu apa yang membuatmu bahagia. Apa yang membuatmu takut. Apa yang kamu impikan. Apa yang ingin kamu capai. Hal-hal kecil apa yang bisa membuat harimu lebih baik.",
        "Aku ingin mengenal kebiasaanmu yang mungkin menurutmu aneh.",
        "Aku ingin tahu cerita-cerita kecil yang mungkin nggak pernah kamu ceritakan kepada banyak orang.",
        "Karena semakin lama aku mengenalmu, semakin aku sadar bahwa mencintai seseorang bukan hanya tentang menyukai bagian yang indah darinya.",
        "Tapi tentang menerima bahwa seseorang datang dengan seluruh dirinya.",
        "Dengan masa lalu, kebiasaan, kekurangan, ketakutan, dan segala hal yang membentuk dirinya sampai menjadi orang yang sekarang.",
        "Dan aku nggak ingin memilih hanya bagian tertentu darimu.",
        "Aku ingin mengenal semuanya.",
        "Karena semuanya itu adalah kamu.",
      ],
    },
    {
      title: "Better Man (Taylor's Version) (From the Vault)",
      artist: "Taylor Swift",
      youtubeId: "PReSQYTFvcs",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku tahu aku bukan seseorang yang sempurna.",
        "Ada banyak hal dalam diriku yang masih harus diperbaiki. Cara berpikir, cara berbicara, cara memahami sesuatu, bahkan mungkin cara mencintai seseorang.",
        "Tapi kalau ada satu hal yang membuatku ingin terus berkembang, itu adalah keinginan untuk menjadi seseorang yang lebih baik.",
        "Bukan karena aku ingin terlihat sempurna di depanmu.",
        "Aku hanya ingin ketika suatu hari kamu melihat ke belakang, kamu bisa merasa bahwa kehadiranku dalam hidupmu bukan sesuatu yang membuatmu menyesal.",
        "Aku ingin belajar mendengarkan lebih baik.",
        "Belajar memahami sebelum menghakimi.",
        "Belajar mengakui ketika aku salah.",
        "Dan belajar bahwa mencintai seseorang bukan hanya tentang mengatakan “aku sayang kamu”, tapi juga tentang bagaimana kita memperlakukan orang itu setiap harinya.",
        "Aku nggak tahu apakah aku akan selalu berhasil.",
        "Mungkin tidak.",
        "Tapi aku ingin terus mencoba.",
        "Karena kalau ada seseorang yang membuatku ingin menjadi versi diriku yang lebih baik, orang itu adalah kamu.",
      ],
    },
    {
      title: "you!",
      artist: "LANY",
      youtubeId: "HEAn4FqXFY4",
      startSeconds: 0,
      cover: "",
      message: [
        "Ada hal lucu tentang bagaimana seseorang bisa perlahan memenuhi banyak bagian dalam hidup kita tanpa kita sadari.",
        "Awalnya cuma namamu di layar.",
        "Lalu menjadi seseorang yang ingin kuceritakan sesuatu.",
        "Kemudian menjadi orang yang ingin kucari ketika ada sesuatu yang membuatku senang.",
        "Sampai akhirnya ada banyak hal yang tiba-tiba mengingatkanku padamu.",
        "Sebuah lagu. Sebuah tempat. Sebuah makanan. Sebuah kalimat. Bahkan hal kecil yang mungkin nggak ada hubungannya sama sekali.",
        "Dan setiap kali itu terjadi, aku cuma bisa tersenyum dan berpikir, “Kenapa lagi-lagi kamu?”",
        "Mungkin karena tanpa sadar kamu sudah menjadi bagian dari terlalu banyak hal dalam hidupku.",
        "Jadi kalau suatu hari kamu mendengar lagu ini dan tiba-tiba teringat kepadaku, aku rasa itu cukup adil.",
        "Karena aku juga sudah terlalu sering melakukan hal yang sama.",
      ],
    },
    {
      title: "Begin Again (Taylor's Version)",
      artist: "Taylor Swift",
      youtubeId: "dXNZaHuKWNA",
      startSeconds: 0,
      cover: "",
      message: [
        "Kalau suatu hari aku diberi kesempatan untuk mengulang semuanya dari awal, aku rasa aku tetap ingin bertemu denganmu.",
        "Mungkin aku akan melakukan beberapa hal dengan cara yang berbeda.",
        "Mungkin aku akan lebih berani mengatakan beberapa hal.",
        "Mungkin aku akan lebih cepat menyadari betapa pentingnya kamu.",
        "Tapi satu hal yang mungkin nggak akan berubah adalah keinginanku untuk mengenalmu lagi.",
        "Karena sekarang aku tahu bahwa seseorang sepertimu bukan seseorang yang ingin kulewatkan begitu saja.",
        "Aku ingin mengulang percakapan pertama. Mengulang rasa penasaran pertama. Mengulang momen ketika aku mulai sadar bahwa ada sesuatu yang berbeda setiap kali berbicara denganmu.",
        "Dan mungkin justru itu yang indah dari sebuah hubungan.",
        "Kita nggak harus menjadi orang yang sama seperti ketika pertama bertemu. Kita boleh berubah. Kita boleh tumbuh.",
        "Dan setiap kali hidup memberikan kita kesempatan untuk memulai bab baru, aku ingin tetap bisa berkata: “Kalau harus dimulai lagi, aku tetap memilih kamu.”",
      ],
    },
    {
      title: "Starting Over Again",
      artist: "Natalie Cole",
      youtubeId: "MpuyU3lPbsw",
      startSeconds: 0,
      cover: "",
      message: [
        "Memulai kembali nggak selalu berarti bahwa sesuatu sebelumnya gagal.",
        "Kadang kita hanya membutuhkan kesempatan untuk melihat sesuatu dari sudut pandang yang berbeda. Untuk belajar dari apa yang sudah dilewati. Untuk menjadi lebih dewasa. Untuk memahami satu sama lain dengan cara yang sebelumnya belum kita mengerti.",
        "Kalau suatu hari nanti kita sampai pada sebuah titik di mana kita merasa harus memulai bab baru, aku ingin kita nggak takut.",
        "Kita nggak harus punya semua jawaban. Kita nggak harus tahu persis ke mana semuanya akan membawa kita.",
        "Kita hanya perlu percaya bahwa selama kita masih mau saling memahami, selalu ada sesuatu yang bisa dibangun kembali.",
        "Dan mungkin setiap awal baru akan terasa sedikit menakutkan.",
        "Tapi kalau orang yang berdiri di sebelahku masih kamu, aku rasa aku akan tetap berani mengambil langkah pertama.",
        "Lagi. Dan lagi.",
      ],
    },
    {
      title: "Last Night on Earth",
      artist: "Green Day",
      youtubeId: "1RTMbmVr3j8",
      startSeconds: 0,
      cover: "",
      message: [
        "Kalau malam ini benar-benar menjadi malam terakhir yang kita punya, aku nggak ingin menghabiskannya dengan memikirkan semua hal yang belum sempat kita lakukan.",
        "Aku ingin duduk di dekatmu. Mendengarkan ceritamu. Melihat caramu tersenyum. Mungkin membicarakan sesuatu yang sebenarnya nggak penting.",
        "Karena kalau benar-benar hanya ada satu malam tersisa, aku rasa yang paling berharga bukanlah tempat yang kita datangi atau sesuatu yang kita miliki.",
        "Tapi siapa yang ada di samping kita.",
        "Dan kalau orang itu adalah kamu, rasanya sudah lebih dari cukup.",
        "Tapi untungnya, kita masih punya hari setelah hari ini. Masih ada besok.",
        "Masih ada banyak lagu yang belum kita dengarkan. Masih ada banyak tempat yang belum kita datangi. Masih ada banyak makanan yang belum kita coba. Masih ada banyak cerita yang belum kita ceritakan.",
        "Jadi untuk sekarang, mari kita jangan berpikir tentang malam terakhir.",
        "Mari kita nikmati malam ini. Dan berharap masih ada banyak malam lain setelahnya.",
      ],
    },
    {
      title: "Magnolia",
      artist: "Magnolia Celebration",
      // ⚠ CEK INI: official audio "Magnolia Celebration - Topic".
      // Jangan pakai 3UdVruU2qGc — itu Laufey (dipakai di /bloom).
      youtubeId: "W9ufcuH04M8",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku nggak tahu kenapa bunga bisa punya kemampuan untuk membuat seseorang mengingat sesuatu.",
        "Mungkin karena bunga punya waktunya sendiri untuk tumbuh, mekar, dan akhirnya layu.",
        "Tapi justru karena waktunya terbatas, kita jadi ingin memperhatikannya lebih lama.",
        "Dan sekarang, entah kenapa, magnolia punya tempat yang sedikit berbeda dalam pikiranku.",
        "Karena ketika aku melihat atau mendengar tentang bunga ini, ada sesuatu yang membuatku teringat kepadamu.",
        "Mungkin karena ada keindahan yang nggak perlu terlalu banyak dijelaskan. Cukup dilihat, lalu dirasakan.",
        "Aku ingin suatu hari nanti ketika kamu melihat bunga magnolia, kamu nggak hanya melihat sebuah bunga.",
        "Aku ingin kamu mengingat satu malam, satu lagu, satu surat, dan seseorang yang pernah membuat bunga itu menjadi bagian kecil dari cerita kalian.",
        "Mungkin itu alasan kenapa lagu ini ada di sini.",
        "Karena dari semua hal yang bisa aku tinggalkan untukmu, aku ingin ada sesuatu yang tetap bisa mengingatkanku kepadamu bahkan ketika aku sedang nggak berada di sana.",
      ],
    },
    {
      title: "Monolog",
      artist: "Pamungkas",
      youtubeId: "-mwsPoerFWU",
      startSeconds: 0,
      cover: "",
      message: [
        "Ada begitu banyak hal yang kadang hanya berani kusampaikan di dalam kepala.",
        "Kalimat yang ingin kukatakan tapi akhirnya hanya kusimpan.",
        "Perasaan yang sebenarnya sederhana, tapi ketika ingin dijelaskan justru menjadi terlalu rumit.",
        "Kadang aku memikirkanmu tanpa alasan. Kadang aku mengulang percakapan kita di kepala. Kadang aku bertanya apakah kamu sadar betapa banyak hal kecil tentangmu yang sebenarnya aku ingat.",
        "Mungkin kamu nggak akan pernah tahu semuanya. Dan mungkin memang nggak semua hal harus dikatakan.",
        "Jadi biarkan beberapa perasaan tetap menjadi monolog kecil yang hanya aku dan pikiranku yang tahu.",
        "Tapi setidaknya sekarang, sebagian kecilnya sudah sampai kepadamu.",
        "Kalau suatu hari kamu bertanya-tanya apakah pernah ada seseorang yang memikirkanmu lebih banyak dari yang kamu sadari, jawabannya mungkin ada di lagu ini.",
      ],
    },
    {
      title: "Heaven",
      artist: "Bryan Adams",
      youtubeId: "3eT464L1YRA",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku nggak tahu seperti apa definisi “rumah” bagi orang lain.",
        "Tapi menurutku, rumah bukan selalu sebuah tempat.",
        "Kadang rumah adalah seseorang.",
        "Seseorang yang membuat kita nggak perlu berpura-pura. Seseorang yang membuat kita merasa cukup hanya dengan menjadi diri sendiri.",
        "Dan ada beberapa momen bersamamu yang membuatku mengerti sedikit tentang perasaan itu.",
        "Nggak ada sesuatu yang luar biasa. Nggak ada dunia yang tiba-tiba berhenti. Hanya ada kamu, aku, dan sebuah momen sederhana.",
        "Tapi entah kenapa, semuanya terasa cukup.",
        "Kalau suatu hari nanti hidup terasa terlalu ramai, terlalu cepat, atau terlalu melelahkan, aku harap kamu masih punya tempat untuk kembali.",
        "Dan kalau suatu saat tempat itu adalah aku, aku akan merasa sangat beruntung.",
        "Karena kalau ada satu hal yang ingin aku berikan kepadamu, mungkin bukan kehidupan yang sempurna. Tapi sebuah tempat di mana kamu selalu merasa diterima.",
      ],
    },
    {
      title: "Bertaut",
      artist: "Nadin Amizah",
      youtubeId: "HyhLsy6b0XI",
      startSeconds: 0,
      cover: "",
      message: [
        "Ada hubungan yang nggak selalu harus dijelaskan dengan kata-kata.",
        "Kita bisa saja sedang sibuk dengan hidup masing-masing. Bisa saja sedang berada di tempat yang berbeda. Bisa saja nggak berbicara sepanjang hari.",
        "Tapi tetap ada sesuatu yang membuat kita merasa dekat.",
        "Seperti benang tipis yang nggak selalu terlihat, tapi tetap menghubungkan dua orang.",
        "Mungkin itulah yang kurasakan tentang kita.",
        "Aku nggak tahu akan seperti apa bentuk hubungan kita beberapa tahun dari sekarang. Aku nggak tahu seberapa jauh hidup akan membawa kita.",
        "Tapi aku berharap, di antara semua perubahan itu, selalu ada sesuatu yang membuat kita bisa saling menemukan jalan pulang.",
        "Karena ada orang-orang yang datang ke hidup kita lalu pergi.",
        "Tapi ada juga seseorang yang meninggalkan jejak begitu dalam sampai keberadaannya terasa bahkan ketika dia sedang jauh.",
        "Dan kamu adalah salah satu orang yang seperti itu bagiku.",
      ],
    },
    {
      title: "Ah",
      artist: "Nadin Amizah",
      youtubeId: "iryd1kZGGH4",
      startSeconds: 0,
      cover: "",
      message: [
        "Kadang aku nggak punya kalimat yang bagus untuk menjelaskan perasaanku kepadamu.",
        "Kadang aku cuma melihatmu, mendengar ceritamu, atau melihat sesuatu yang mengingatkanku padamu, lalu di dalam kepala cuma ada satu reaksi sederhana: “Ah…”",
        "Seperti ada sesuatu yang tiba-tiba memenuhi dada, tapi terlalu sederhana untuk dijelaskan.",
        "Mungkin begitulah rasa sayang. Nggak selalu datang dalam bentuk kata-kata besar.",
        "Kadang hanya berupa keinginan untuk tahu apakah kamu sudah makan. Keinginan untuk mendengar bagaimana harimu. Keinginan untuk membuatmu tertawa ketika kamu sedang lelah. Atau sekadar merasa senang karena tahu kamu baik-baik saja.",
        "Hal-hal kecil yang mungkin terlihat biasa.",
        "Tapi kalau dikumpulkan semuanya, ternyata menjadi sesuatu yang besar.",
        "Sesuatu yang membuatku sadar bahwa ternyata aku benar-benar sayang sama kamu.",
      ],
    },
    {
      title: "Rayuan Perempuan Gila",
      artist: "Nadin Amizah",
      youtubeId: "gIsoLyQX7W8",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku mungkin bukan orang yang paling pandai menyampaikan perasaan.",
        "Kadang terlalu banyak berpikir. Kadang terlalu khawatir. Kadang ingin mengatakan sesuatu tapi malah mencari seribu cara untuk menyampaikannya.",
        "Dan mungkin dari luar semuanya terlihat sedikit berlebihan.",
        "Tapi kalau ada satu hal yang nggak pernah berlebihan bagiku, itu adalah rasa sayangku kepadamu.",
        "Aku mungkin nggak selalu tahu cara terbaik untuk menunjukkannya.",
        "Tapi aku ingin kamu tahu bahwa di balik semua perhatian kecil, semua pertanyaan, semua kekhawatiran, dan semua hal yang mungkin kadang terasa berlebihan itu, ada seseorang yang benar-benar peduli kepadamu.",
        "Seseorang yang ingin melihatmu bahagia. Seseorang yang ingin tahu ketika kamu sedang nggak baik-baik saja. Seseorang yang mungkin sedikit terlalu sayang.",
        "Tapi kalau memang harus sedikit gila karena seseorang, aku rasa aku nggak keberatan kalau orangnya adalah kamu.",
      ],
    },
    {
      title: "honey",
      artist: "boy pablo",
      youtubeId: "glVIdLeLmvo", // pakai official audio (MV asli cuma di Vimeo)
      startSeconds: 0,
      cover: "",
      message: [
        "Setelah semua lagu yang penuh dengan perasaan dan cerita, aku rasa kita butuh satu lagu yang sedikit lebih sederhana.",
        "Nggak perlu terlalu banyak kata. Nggak perlu cerita yang berat. Cukup sesuatu yang manis.",
        "Karena ada sisi dari rasa sayang yang memang sesederhana itu.",
        "Memanggil seseorang dengan nama kecil. Tersenyum ketika melihat namanya. Menyimpan foto yang sebenarnya nggak terlalu istimewa tapi tetap nggak pernah tega dihapus. Atau tiba-tiba merasa bahagia hanya karena mendapatkan pesan sederhana darinya.",
        "Aku suka bagian hubungan kita yang seperti itu.",
        "Bagian yang nggak perlu dijelaskan kepada siapa pun. Bagian yang mungkin cuma kita yang mengerti.",
        "Dan kalau suatu hari kamu mendengar lagu ini, semoga kamu ingat bahwa pernah ada seseorang yang melihatmu bukan hanya sebagai seseorang yang dia cintai, tapi juga sebagai seseorang yang selalu berhasil membuat hari-harinya terasa sedikit lebih manis.",
      ],
    },
    {
      title: "Nothing's Gonna Change My Love for You",
      artist: "George Benson",
      youtubeId: "4tf0ZjN1UPE",
      startSeconds: 0,
      cover: "",
      message: [
        "Aku nggak bisa menjanjikan bahwa hidup akan selalu berjalan sesuai yang kita inginkan.",
        "Kita akan berubah. Kita akan tumbuh. Prioritas kita mungkin berubah. Kita akan bertemu banyak orang, mengalami banyak hal, dan mungkin melihat dunia dengan cara yang berbeda dari sekarang.",
        "Tapi di tengah semua perubahan itu, ada sesuatu yang ingin selalu aku usahakan untuk tetap sama.",
        "Rasa sayangku kepadamu.",
        "Bukan berarti semuanya akan selalu sempurna. Bukan berarti kita nggak akan pernah punya masalah. Dan bukan berarti aku punya jawaban untuk semua hal yang akan terjadi di masa depan.",
        "Aku cuma ingin ketika suatu hari nanti kamu melihat kembali ke masa ini, kamu tahu bahwa pernah ada seseorang yang benar-benar tulus menyayangimu.",
        "Seseorang yang menikmati setiap hal kecil bersamamu. Seseorang yang bersyukur pernah mengenalmu.",
        "Dan seseorang yang, meskipun waktu terus berjalan, akan selalu menyimpan bagian kecil dari cerita ini di dalam hatinya.",
      ],
    },
    {
      title: "Shape of My Heart",
      artist: "Backstreet Boys",
      youtubeId: "OT5msu-dap8",
      startSeconds: 0,
      cover: "",
      message: [
        "Kalau kamu sudah sampai di lagu terakhir, berarti kamu sudah melewati semuanya.",
        "Dua puluh empat lagu. Dua puluh empat cerita kecil. Dua puluh empat alasan yang sengaja aku tinggalkan di sini untukmu.",
        "Sebenarnya aku nggak tahu apakah nanti kamu akan mengingat semua pesan yang aku tulis. Mungkin beberapa akan kamu lupa. Mungkin beberapa hanya akan menjadi tulisan yang pernah kamu baca sekali.",
        "Dan itu nggak apa-apa.",
        "Aku nggak membuat semua ini supaya kamu harus mengingat setiap katanya. Aku cuma ingin meninggalkan sesuatu yang bisa kamu temukan kembali kapan pun kamu mau.",
        "Karena mungkin suatu hari nanti kita akan berada di tempat yang berbeda. Mungkin kita akan sibuk dengan kehidupan masing-masing.",
        "Mungkin beberapa lagu dari playlist ini akan terdengar secara nggak sengaja ketika kamu sedang pergi, sedang sendiri, sedang bahagia, atau bahkan ketika kamu sedang menjalani hari yang biasa saja.",
        "Dan ketika lagu itu terdengar, aku berharap kamu berhenti sebentar. Bukan untuk merasa sedih. Bukan untuk memikirkan sesuatu yang berat. Tapi cukup tersenyum dan berkata dalam hati, “Aku pernah punya seseorang yang menyayangiku seperti itu.”",
        "Karena sebenarnya itulah alasan aku membuat semua ini.",
        "Aku nggak ingin menjadi seseorang yang hanya kamu ingat ketika membuka website ini. Aku ingin, sedikit demi sedikit, lagu-lagu yang memang sudah kamu sukai sejak awal memiliki cerita baru.",
        "Cerita tentang seseorang yang pernah mendengarkan lagu yang sama dan berpikir tentang kamu. Tentang seseorang yang ingin membuatmu tersenyum. Tentang seseorang yang ingin meninggalkan sedikit bagian dari dirinya di antara lagu-lagu yang kamu cintai.",
        "Jadi kalau nanti salah satu dari 24 lagu ini terdengar di luar sana… di perjalanan, di kamar, di sebuah kafe, di malam yang sepi, atau entah di mana pun kamu berada… aku harap selama beberapa detik saja, kamu ingat aku.",
        "Dan kalau kamu benar-benar mengingatku, aku harap yang kamu ingat bukan hanya kata-kata dari halaman ini. Tapi semua hal kecil yang pernah kita lewati. Semua tawa. Semua percakapan. Semua malam. Semua cerita. Semua rasa. Dan semua alasan kenapa kita pernah sampai sejauh ini.",
        "Karena pada akhirnya, mungkin cinta memang nggak selalu tinggal dalam bentuk seseorang. Kadang dia tinggal dalam sebuah lagu. Dalam sebuah tempat. Dalam sebuah aroma. Dalam sebuah foto. Dalam sebuah kalimat.",
        "Dan mungkin, mulai hari ini, sebagian kecil dari 24 lagu ini akan selalu punya namaku di dalamnya.",
        "Thank you for listening.",
        "And thank you for being the most beautiful part of my soundtrack. ♡",
      ],
    },
  ] as SoundtrackSong[],

  // 🌷 Penutup — layar singkat setelah lagu terakhir. Sengaja pendek karena
  // surat lagu ke-24 sudah jadi klimaksnya. TIDAK menautkan ke /bloom.
  ending: {
    title: "Itu tadi — semuanya.",
    line: "Tapi semoga ini bukan akhirnya. ♡",
    message: [],
    backLabel: "Back to our space ♡",
    replayLabel: "putar dari awal",
  },
} as const;
